### PR TITLE
Add 96Boards Carbon as a probe host

### PR DESCRIPTION
**Pull request by daniel-thompson**
The carbon contains two SoCs, an STM32 (host) and an nRF51 (BLE). The
STM32 implements the probe and allows the board to reprogram its own
radio firmware!

### CODE REVIEW

**Comment by daniel-thompson** [comment]
Any new on this? I can see a few changes have landed on the mainline since I posted. It looks like the merge remains clean but if you think a rebase and re-test is needed then just let me know...

**Comment by daniel-thompson** [comment]
@pfalcon reported a typo in the Carbon's Readme.md so whilst fixing that I have done the rebase anyway (there were no conflicts).

Any more changes needed?

**Comment by pfalcon** [comment]
+1 for merging this

**Comment by Mani-Sadhasivam** [comment]
Any reason for not merging this? I've tested this port on 96Boards Carbon to flash and debug STM32F411xE based custom board. It would be good to have this support in mainline as the usecase will more likely to increase.

**Comment by pfalcon** [comment]
In regard to recently added "$3 Board Support" label. Well, the target board of this patch, 96Boards Carbon https://www.96boards.org/product/carbon/ , isn't a "$3 board". It's not as expensive as an original BMP too, but it's nowhere near being a real SWD programmer - it's a board intended to explore 6LoWPAN connectivity using Zephyr RTOS http://zephyrproject.org/ . The only realistic usecase for running BMP firmware on it is to program one onboard MCU with another (as mentioned in the description, the board has 2 - one "application MCU", and another is "BLE controller").

Hopefully this might help to assess a level of conflict of interest for maintainers' spending effort to merge this patch. (Otherwise, we're just happy to allow user to self-program the BLE part, and love to merge things upstream ;-) ).

**Comment by dragonmux** [comment]
Sorry this PR has dragged on! Thank you for the contribution.

Once the v1.8 release cycle has been completed, we'll try and review this in short order and see about merging it. This shouldn't have dragged on as long as it has.

**Review by dragonmux — APPROVED** [review]
LGTM

**Review by esden — APPROVED** [review]
I do have to ask if the copyright in the file headers correct? I assume the files mostly just a copy from one of the other host boards with minor modifications? If so that is fine. But in general it would be good to keep some record who added the code.

That said, there are two reasons why I am ok with merging this PR none the less:
1. The host board support will be consolidated with the upcoming build system update. So the duplicated files will essentially be deleted and only the differences kept as a config file.
2. This patch is sitting for so long that I am not expecting the original authors to come back to make copyright header fixes. 

Keeping all that in mind. I will approve this PR.

**Pull request merged**
