### PR TITLE
Added support for kinetis MK20DX256 chip

### PR DESCRIPTION
**Pull request by vedranMv**
## Detailed description

This PR adds support for a MK20DX256 chip in `kinetis.c`. It specifies flash region, both RAM segments and FlexNVM. It doesn't, however, add support for FlexRAM that this chip features. That support seems to lack from all other kinetis targets too, I guess due to the complication that this region can be configured both as RAM and EEPROM.

One of the comments made on the branch was to use defines instead of addresses directly, which doesn't seem to be common practice in `kinetis.c`. So for now I added the values directly as function arguments. If that's still desired, I can make a change :)

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [ ] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware)) - Linker fails with ROM overflowing (arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621, but building main branch fails with the same error). This PR increases ROM consumption by 0.03%.
* [x] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

The following was tested on Tiva ICDI platform, with GDB 8.3.1:
* load firmware to a MK20 target
* run target
* set & remove breakpoint
* set & remove watchpoint
* pause target, and while paused
  * get general registers
  * get stack trace
  * watch code variable
  * inspect hardware peripheral registers
  * read out 1k of random RAM
  * read out 1k of random flash
* resume target
* disconnect & confirm target continues to run

## Closing issues

No known open issues.

### CODE REVIEW

**Comment by dragonmux** [comment]
Before we review, do note that we recommend upgrading your ARM GCC to GCC 12.2.Rel1 - this has better diagnostics and better code generation, which is why the resulting binaries from it do fit in Flash.

**Comment by dragonmux** [comment]
> One of the comments made on the branch was to use defines instead of addresses directly, which doesn't seem to be common practice in `kinetis.c`. So for now I added the values directly as function arguments. If that's still desired, I can make a change :)

Yeah, this needs to change - so please use defines in this PR so less has to be fixed later in a follow-up PR.

**Review by dragonmux — COMMENTED** [review]
Taking into account the comment about defines, the rest of this looks great and we'll be happy to merge this once that's been sorted.

**Comment by vedranMv** [comment]
Changed to defines :)

Still can't get it to build though, these are the commands:
```
~$ meson setup build-cross --cross-file cross-file/arm-none-eabi.ini -Dprobe=native
(trimmed)
Black Magic Debug 1.10.0

  Targets
    Cortex-A/R support       : NO
    Cortex-M support         : YES
    RISC-V 32-bit support    : NO
    RISC-V 64-bit support    : NO
    Energy Micro parts       : YES
    HC32 parts               : YES
    LPC series parts         : YES
    nRF series parts         : YES
    Kinetis series parts     : YES
    Renesas parts            : YES
    RP2040                   : YES
    ATSAM series parts       : YES
    STM32 (and clones) parts : YES
    Texas Instruments parts  : YES
    Xilinx parts             : NO

  Probe
    Name                     : Black Magic Probe (native)
    Platform                 : STM32F1
    Bootloader               : Black Magic Debug Bootloader
    Load Address             : 0x8002000

  Black Magic Debug
    Debug output             : NO
    RTT support              : YES
    Advertise QStartNoAckMode: NO
    Building Firmware        : YES
    Building BMDA            : YES

  Subprojects
    libopencm3               : YES 2 warnings
 (trimmed)
~$ meson compile -C build-cross
 (trimmed)
/home/vedranmv/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: blackmagic_native_firmware.elf section `.ARM.exidx' will not fit in region `rom'
/home/vedranmv/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: address 0x8020e4c of blackmagic_native_firmware.elf section `.text' is not within region `rom'
/home/vedranmv/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: region `rom' overflowed by 4044 bytes
Memory region         Used Size  Region Size  %age Used
             rom:      135116 B       128 KB    103.09%
             ram:        5672 B        20 KB     27.70%
collect2: error: ld returned 1 exit status
[447/498] Compiling C object blackmagic.p/src_target_samd.c.o
ninja: build stopped: subcommand failed.
```

**Comment by dragonmux** [comment]
You have RTT enabled in that build, which presently does not fit on native without turning off some targets due to the space constraint - this looks to be the cause.

**Review by dragonmux — APPROVED** [review]
LGTM, merging once the builds complete. Thank you for the contribution!

**Comment by vedranMv** [comment]
Great, thanks a lot for guidance. Enjoy your weekend!

**Pull request merged**
