### PR TITLE
Symbolically define the USB endpoint addresses and enable them to be overridden by platform if required

### PR DESCRIPTION
**Pull request by sidprice**
If a platform requires the use of different USB endpoints they may be defined in platform.h for the platform.

### CODE REVIEW

**Comment by Vestrel** [comment]
I think names should also reflect endpoint type (in/out)

**Comment by UweBonnes** [comment]
What about e.g. xxx_EP_OUT and xxx_EP_IN?

**Comment by sidprice** [comment]
@UweBonnes Good idea, just because I ALWAYS confuse In and Out, would this be correct?

#define CDCACM_GDB_DATA_EP_IN 0x81

**Comment by UweBonnes** [comment]
0x80 + x seesm to be the IN-EPs. Recheck with lsusb -v

**Comment by sidprice** [comment]
@UweBonnes Names changed to reflect IN/OUT

**Comment by UweBonnes** [comment]
"make all_platforms" stops in launchpad-icdi

**Comment by sidprice** [comment]
Sorry, I thought I had run each platform build, I was not aware of "make all_platforms", however, on Windows that does not work. I will create a new issue for that. All platforms now build.

Note I do not have hardware to test them so we should probably request someone who has launchpad-icdi, hydrabus, stlink, and swlink to check the builds.

**Comment by UweBonnes** [comment]
I also do not have all platforms and do not test all platforms. But at least all platforms should compile, so that a "git bisect" can succeed it at a later point in time when somebody with that platform finds a problem.  Your code looks like  a simple substitution without code change, so chances for colateral damage are small (famous last words ;-)

**Comment by sidprice** [comment]
I agree ;-)

**Comment by sidprice** [comment]
I would like to try and prepare a PR for ctxLink and having this PR merged is necessary before that because ctxLink uses the end point names.

**Comment by sidprice** [comment]
@dragonmux It looks like my PR was covered by #956 and already merged. So, this PR can be closed, I think.

**Comment by dragonmux** [comment]
Yeah, seems reasonable - closing

**Pull request closed without merging**
