### PR TITLE
Rework/cleanup TARGETID handling

### PR DESCRIPTION
**Pull request by perigoso**
built on top of #1143 mind the extra commits

This tries to improve readabilty and correctness in the initialization of the dp and the reading and usage of targetid

This needs some more thorough testing, but so far it looks good, on some embedded jlink targets target id is now being read where it was not before

changed the logic in the target probe "selection" including the change mentioned on discord

~~note: i think we can, and should, safely move the target id reading inside the dp_init method, but I'll leave that for a future cleanup~~

### CODE REVIEW

**Comment by perigoso** [comment]
This PR also supersedes #1141, so that may be closed if this is to be merged

**Comment by perigoso** [comment]
Tested probe (hosted and native) with success on:
- Nordic nRF52
- SAMS70J19A
- Atmel SAM3U
- 1 Unknown ARM Cortex-M Designer 0x423 Part ID 0x150 (Renesas RA6M2)
- RP2040

**Comment by dragonmux** [comment]
Please rebase this then we'll review and merge it.

**Comment by perigoso** [comment]
ready.

**Comment by perigoso** [comment]
should be good to go right after 1143 merge

**Review by dragonmux — APPROVED** [review]
LGTM! We'll merge once we've tested against our Tiva-C target too

**Pull request merged**
