### PR TITLE
Traceswo enhanced w fifo

### PR DESCRIPTION
**Pull request by anyn99**
I was finally able to improve the traceswo (Manchester encoding).
I had to add a fifo to allow async buffering, maybe it would be also useful in other parts of the project?

The output works very reliable now up to 115Khz SWO frequency here.

### CODE REVIEW

**Comment by valff** [comment]
I'm using this patch today and haven't encountered any problems. It works with my usual workflow, but I haven't done any stress tests.

**Comment by anyn99** [comment]
Ah, Im happy someone is trying it successfully! What i meant of course is a speed of 215kHz was tested successfully

**Comment by UweBonnes** [comment]
Please correct style issues. Otherwise, do you need to changes so many Makefile.inc?

**Comment by UweBonnes** [comment]
I have rebased the patch. Can people try again?

**Comment by koendv** [comment]
Have I made an error, or does this not compile on stlink?

**Comment by UweBonnes** [comment]
Are you "koendv"  also "anyn99"?

**Comment by koendv** [comment]
No.

**Comment by UweBonnes** [comment]
Then I do not understand why you ask in this thread "if you have made an error"?

**Comment by dragonmux** [comment]
Thank you for the contribution @anyn99! Sorry this PR has dragged on without merge.

We are looking to get this merged for v1.9, if possible could we ask you to please rebase this against main? If not, then no worries, we'll do it to a feature branch on repo ourself and preserve authorship so you get credited in the release notes.

**Comment by dragonmux** [comment]
Given this appears to be a dead PR, we have rescued the contribution to a feature branch where we have rebased it and addressed some stylistic and functional issues that showed up in review. A new PR that supersedes this one has been opened as #1092.

Sorry to see this grind to a halt because it wasn't addressed in a timely manner, and thank you for the contribution. It is appreciated and we have preserved authorship in the new PR so you will be credited for the work in the release notes.

**Pull request closed without merging**
