### PR TITLE
Feature: STM32H5xx and STM32H7xx support

### LINKED ISSUE #1440: Feature request: STM32H503/H562/H563/H573 support.
STM Recently released the STM32H5 processors with a Cortex-M33 core.

https://www.st.com/en/microcontrollers-microprocessors/stm32h5-series.html

It would be awesome if BMP could support these processors.

I have NucleoH503 and H563 boards here for testing if needed.

I had a look at the flash chip registers, which are not the same as on previous MCUs.  It's dual-bank and has many security related features.

image

FWIW: I poked around in the OpenOCD code and tried a few things out there, and made some progress, and also posted on the OpenOCD mailing list but there has been zero replies to either my ML post or SF issue, here: https://sourceforge.net/p/openocd/tickets/389/  I'm hoping that perhaps BMP support might come sooner.

I'm primarily interested in the STM32H562/H563 MCUs (the H563 being mostly the same as a H562 + Ethernet)

Here's a links to the Nucleo boards:
* https://www.st.com/en/evaluation-tools/nucleo-h563zi.html
* https://www.st.com/en/evaluation-tools/nucleo-h503rb.html

Mouser links:

* https://eu.mouser.com/ProductDetail/STMicroelectronics/NUCLEO-H563ZI
* https://eu.mouser.com/ProductDetail/STMicroelectronics/NUCLEO-H503RB

### PR DESCRIPTION
**Pull request by dragonmux**
## Detailed description

This PR adds support for the STM32H5 series processors, and improves support for the STM32H7 series processors.

STM32H5 support includes support for Flash programming and mass erase, but does not yet include support for the option bytes

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

Fixes #1440

### CODE REVIEW

**Comment by hydra** [comment]
Flash writes fail however.

[log-20230411-1903.txt](https://github.com/blackmagic-debug/blackmagic/files/11203716/log-20230411-1903.txt)

```
ap_mem_write_sized @ 8000000 len 8192, align 4: 00 20 00 20 1f 06 00 08 00 f0 00 b8 f0 b5 03 af ...
remote_adiv5_mem_write_bytes error around 0x08000000
```

**Comment by dragonmux** [comment]
We have now tested this against the Nucleo-H503 board and confirmed all aspects of target support work via native hardware. Nucleo-H563 testing remains to be done but we are hopeful that will also just work.

**Review by esden — DISMISSED** [review]
LGTM

**Review by esden — APPROVED** [review]
LGTM*2 ;)

**Pull request merged**
