### PR TITLE
blackpill, bluepill: led, NRST, STM32F401CCU6, STM32F401CEU6

### PR DESCRIPTION
**Pull request by koendv**
## Detailed description

Various small patches.
This PR is submitted so people who search for these features find it. 

- blackpill:
  - LED blinks if bmp is active (like on stlinkv2)
  - support for NRST pin in case target needs to connect under reset
  - same binary for STM32F401CCU6, STM32F401CEU6 and STM32F411CEU6
  - compiles with: ``make PROBE_HOST=blackpillv2 ENABLE_RTT=1``
  
- blue pill:
  - LED blinks if bmp is active (like on stlinkv2)
  - compiles with: ``make PROBE_HOST=stlink BLUEPILL=1 ENABLE_RTT=1``

HTH

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

### CODE REVIEW

**Comment by dragonmux** [comment]
Did you mean to close this right after opening it?

**Comment by koendv** [comment]
On Sun, 06 Nov 2022 07:14:02 -0800
Rachel Mant ***@***.***> wrote:

> Did you mean to close this right after opening it?
> 

This is how I patch bmp for my personal use. 
I'm not certain whether it's useful to others.

koen

**Comment by dragonmux** [comment]
Many of the changes here look quite useful in general for those platforms and a quick code review says we'd be happy to merge, so if you do wish to contribute these, we'll be happy to merge them.

The only patch we're unwilling to take is the linker script one because while it's a fix for that problem, it's not really the right fix (and we can't do the right fix till v2) - the correct fix here is 3 linker scripts and an option to pick between the 3 processors as separate platforms, but this can't be done in the current build system without causing problems

**Comment by koendv** [comment]
This is a pleasant, unexpected surprise.
OK. I've dropped the linker patch.

koen

**Review by dragonmux — APPROVED** [review]
LGTM, merging once the build finishes

**Pull request merged**
