### PR TITLE
Fix: Add blackpill-f4 to meson CI

### PR DESCRIPTION
**Pull request by ALTracer**
## Detailed description

* After the removal of makefiles, none of the blackpill-f4 binary firmware autobuilds survived. This creates two problems: users can't get a prebuilt image from `main` CI; and contributors do not get platform-specific code checked by PR CI.
* This PR adds the three blackpill-f4 flavours as-is from cross-files to build-linux probe matrix in both workflows.

size-diff pass does not produce a downloadable artifact.
`scripts/meson-build-all.sh` is unused.

I noticed you've got 5 flavours of `native` now, but I'm not adding them to build-PR.yml, because target driver code is checked on other adapter builds, and platform code can be checked once per platform.

Finally, I'm adding the four newly added/extracted and hence disabled groups of targets (apollo3.c; ch32,gd32,mm32 in stm32f1.c) to blackpill-f4 cross-files such that size-diff reflects their impact on binary size. Please confirm whether this needs to be expanded to all other big flash platforms.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))
* [x] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

### CODE REVIEW

**Review by dragonmux — APPROVED** [review]
This LGTM, please rebase it on `main` and we'll get it merged. Thank you for the contribution!

**Comment by ALTracer** [comment]
Rebased.
Inaccuracy: the 5 flavours of `native` are NOT built per `build-and-upload.yml` triggered by pushes to `main`. But they are built for PR sync-pushes. Is this what you intended? I'm not touching those here, but sounds like users might expect `native` fw on `main`, too?

**Comment by dragonmux** [comment]
It is not what we intended and that is in fact another oversight on our part. If you wanted to include adding those flavours to build-and-upload before we merge, that would be most welcome.

**Comment by ALTracer** [comment]
Added 4 lines to the other CI matrix. Please check the commit message.
Extends and/or fixes #1968, I think.

**Pull request merged**
