### PR TITLE
Fix: AT32F403A/407 dual bank flash support

### PR DESCRIPTION
**Pull request by ALTracer**
## Detailed description

* Support for Artery AT32F403A "Mainstream" devices introduced in #1151 declares only the common/minimum 256 KiB of flash in first bank.
* This PR increases the writable flash size to full 512 KiB in first bank and introduces logic to enable directing erases/writes to second 512 KiB bank, using the existing XL-density part_id checks of stm32f1 flash driver API.

I tested the idea by dropping the dual-bank 0x430U check altogether, and an AT32F403ACGU7 target (WeAct.BlackPill) gets written with my test payload with a long zeroed .rodata array, which passes the check in-payload, mass erase also works (checked with gdb x/16zw 0x08080000 as there is no blank-check routine in BMD). There is no obvious reason to me why at least the first 512 KiB bank wasn't declared with full size.

A related change includes updating no-op aliases for `at32f40x_probe()` I renamed from `at32f4xx_probe()`, and for new `at32f43x_probe()`, such that the at32f43x.c translation unit can be dropped from Makefile target driver sources list.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [ ] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

Closes my #1542 point 1.

### CODE REVIEW

**Review by dragonmux — APPROVED** [review]
LGTM, we'll run some tests on STM32F1's - see if we can find one on our desk that uses the dual bank 0x430U check - and verify that this all till works after. After checking and assuming nothing is broken, we'll get this merged.

Thank you for the contribution!

**Comment by ALTracer** [comment]
Actually hold on, nothing in at32f40_probe/_detect writes the target->part_id, which is why my testing `hosted` build failed to erase and write into the second bank. I'll need to add that first. Not marking as WIP/Draft either.
W.r.t. regress-testing XL-density dual-bank stm32f1 targets -- yes please, check on some if you have them reachable (I don't seem to have any, just the Medium Density). I only delegated/extracted the check, but it doesn't lift the requirements for testing on live devices.

**Comment by dragonmux** [comment]
Is this ready for re-review?

**Comment by dragonmux** [comment]
We were unsure as you hadn't let us know to stay the request to hold. We'll get this review in a bit then 🙂

**Review by dragonmux — APPROVED** [review]
This all looks good to us now - so, based on the eager merge policy in the face of us not having any XL parts to test with, we're going to merge this and see what people report back with it on `main`.

Thank you for the contribution!

**Pull request merged**
