### PR TITLE
Changed blackpillv2 linker script to use only 256k flash and 64k RAM …

### PR DESCRIPTION
**Pull request by Garag**
…to be compatible with stm32f401cc

See also Issue https://github.com/blackmagic-debug/blackmagic/issues/1048

### CODE REVIEW

**Comment by perigoso** [comment]
I would create a new linker `blackpillv1` and use that by default, in the future it might become an option, and it's better documented

**Comment by esden** [comment]
Thank you for your contribution @Garag The board you are attempting to change is specifically [BlackPill V2](https://stm32-base.org/boards/STM32F411CEU6-WeAct-Black-Pill-V2.0) (as the name of the target indicates). Not V1.2 or V3.0. So I will not be able to merge this patch as it is intended for other versions of the board not V2.

In general the policy is to not tack on platform variants onto each other, unless the firmware will be guaranteed to always work and take advantage of the hardware at hand. Each platform has to stay self contained with a specific pin-out and chip in mind. If changes are needed, you either have to add another target platform sub-directory or implement some runtime system for auto-detection of the host chip you have at hand. The latter would be the most powerful but also most difficult solution to implement. You are welcome to work on that and a patch that consolidates blackpill boards into one single firmware is something we can consider merging. Otherwise, if you want to support your specific blackpill hardware version, please make it a separate platform with the correct linker script, pin out and readme.

You are welcome to continue the discussion about this in the issue itself. I will be posting a copy of the above there too.

**Comment by djix123** [comment]
I do wonder if its better to accept the patch - then the blackpill platform will work with all variants of the [blackpill](https://github.com/WeActTC/MiniSTM32F4x1). Seems odd to have arbitrary support for V2 (that happens to work for V3 and not V1) when supported all three versions is straightforward.

**Comment by perigoso** [comment]
In this case it might make sense to rename the platform `blackpill` removing the arbitrary version, if they really are all compatible, which is likely, and have a build variable with the version, that in this case should only affect the linker

**Comment by perigoso** [comment]
I have some ideas to make handling these annoyances easier in the future, if the project switches to meson

**Comment by Garag** [comment]
The changed linker script will work with all Blackpill borads with a STM32F4xx. But i thing there is a Blackpill with a STM32F10x. Maybe a name like blackpill-f4 is better.
As the only change is the linker script, it is not possible to decide about the variant at runtime.

**Comment by perigoso** [comment]
Hm, if that is the case i start to align more with esdens opinion

**Comment by djix123** [comment]
I think what we are discussing is the WeAct TC BlackPill based on the F4. There is a BlackPill (RobotDyn, for example made them) based on the STM32F103 ... but these will work with PROBE_HOST=stlink for example. Better name maybe 'weact-blackpill' or 'weact-blackpill-f4' then the original patch will work for all variations of that board.

**Comment by Garag** [comment]
WeAct seems to have only the F4 BlackPill. From RobotDyn i know a BlackPill like board with a STM32F303CC on it.

**Pull request closed without merging**
