### PR TITLE
Feature: Renesas RZ/A1LU support

### PR DESCRIPTION
**Pull request by dragonmux**
## Detailed description

This PR implements support for the Renesas RZ series parts and specifically the RZ/A1LU Cortex-A9 processor. This was requested by a user and has been tested on real hardware.

The Flash routine speed is low, however there's not too much can be done about that without a Flash stub for now as all memory accesses have to go via the core using multiple instruction launches. This is just a problem with how Cortex-A/R debug works and is non-trivial to solve.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))
* [x] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

### CODE REVIEW

**Comment by esden** [comment]
@dragonmux do you think it is safe to ignore the lint error here?

**Comment by dragonmux** [comment]
It is, however on review the F072 change needs dropping as it looks like there's a build logic mistake for when the renesas_rz.c code gets included that needs fixing before merge

**Comment by esden** [comment]
Ok, sounds good, I will hold off on merging this PR for now. Let me know when the build issue is resolved. :)

**Comment by dragonmux** [comment]
That build issue should now be resolved - our bad for forgetting that part of the Meson build system logic around enabled targets had changed and not updating this branch with that!

**Review by esden — APPROVED** [review]
LGTM

**Pull request merged**
