### PR TITLE
Fix: ADIv5 early AP accesses trigger aborts, corrupting DP writes

### LINKED ISSUE #1117: Flashing fails over CMSIS-DAP at high speed
This may well relate to #1105 

If you flash at high speed over the CMSIS-DAP interface quite often the results are incorrect and fail `compare-sections`;

```
(gdb) file build/STM32F427.elf
(gdb) monitor frequency 25000000
Max SWJ freq 017d7840
(gdb) load
Loading section .isr_vector, size 0x1ac lma 0x8000000
Loading section .text, size 0x14d0 lma 0x80001ac
Loading section .rodata, size 0x4c lma 0x800167c
Loading section .ARM, size 0x8 lma 0x80016c8
Loading section .init_array, size 0x4 lma 0x80016d0
Loading section .fini_array, size 0x4 lma 0x80016d4
Loading section .data, size 0xc lma 0x80016d8
Start address 0x80015b8, load size 5860
Transfer rate: 22 KB/sec, 488 bytes/write.
(gdb) compare-sections 
Section .isr_vector, range 0x8000000 -- 0x80001ac: matched.
Section .text, range 0x80001ac -- 0x800167c: MIS-MATCHED!
Section .rodata, range 0x800167c -- 0x80016c8: matched.
Section .ARM, range 0x80016c8 -- 0x80016d0: matched.
Section .init_array, range 0x80016d0 -- 0x80016d4: matched.
Section .fini_array, range 0x80016d4 -- 0x80016d8: matched.
Section .data, range 0x80016d8 -- 0x80016e4: matched.
warning: One or more sections of the target image does not match
the loaded file

(gdb) 
(gdb) monitor frequency 10000000
Max SWJ freq 00989680
(gdb) load
Loading section .isr_vector, size 0x1ac lma 0x8000000
Loading section .text, size 0x14d0 lma 0x80001ac
Loading section .rodata, size 0x4c lma 0x800167c
Loading section .ARM, size 0x8 lma 0x80016c8
Loading section .init_array, size 0x4 lma 0x80016d0
Loading section .fini_array, size 0x4 lma 0x80016d4
Loading section .data, size 0xc lma 0x80016d8
Start address 0x80015b8, load size 5860
Transfer rate: 23 KB/sec, 488 bytes/write.
(gdb) compare-sections 
Section .isr_vector, range 0x8000000 -- 0x80001ac: matched.
Section .text, range 0x80001ac -- 0x800167c: matched.
Section .rodata, range 0x800167c -- 0x80016c8: matched.
Section .ARM, range 0x80016c8 -- 0x80016d0: matched.
Section .init_array, range 0x80016d0 -- 0x80016d4: matched.
Section .fini_array, range 0x80016d4 -- 0x80016d8: matched.
Section .data, range 0x80016d8 -- 0x80016e4: matched.
(gdb) 
```
This test passes on openocd (with suitable adjusted commands).

Test was conducted using ORBTrace V1.1.0InProgress and STM32F427. Contact me for the elf file if it's useful.

### PR DESCRIPTION
**Pull request by dragonmux**
## Detailed description

Due to the excellent work by @mubes on ORBTrace and the CMSIS-DAP interface it features that BMDA can use, it was found that BMP was, after doing a Debug Port (DP) write, under certain conditions then immediately following it with an Access Port (AP) access that fires an abort. This flushes the queue on the DP and causes data corruption that's especially noticeable when trying to Flash a part.

To trigger this bug requires crossing a threshold access speed, and should be possible on native hardware, albeit very difficult. ARM's own advice is to perform a read on the DP or a safe register on the AP, triggering a wait state till the write completes. This makes accesses safe by functioning as a barrier.

This PR implements the DP read version of the fix which provides the least slowdown (a 53KB/s Flash slows down down to 52KB/s with this patch vs down to 51KB/s when using the AP version of the fix).

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

Fixes #1117

### CODE REVIEW

**Review by esden — APPROVED** [review]
LGTM

**Comment by mubes** [comment]
Oh, and DP and AP are the wrong way around in the description... What
happens is that the DP can cache a write to an AP in order to improve
performance by pipelining, but if activity is performed on the DP which
does not wait for that pending AP write to complete then an error will be
returned and the write will not complete. This is fixed by performing a
read-after-write which will not complete until the pended write has
completed.

**Comment by mubes** [comment]
@zyp deserves a mention in dispatches for this one too. It was most
definitely a joint effort. After quite a lot of kicking possible failure
causes around he was the one that eventually postulated the mode that
turned out to trigger the errant behaviour!

**Comment by dragonmux** [comment]
Fair notes, we'll update the description then.

**Pull request merged**
