### PR TITLE
[WIP] Applet API proposal

### PR DESCRIPTION
**Pull request by zwizwa**
WIP: This is not intended to be merged as is, just as a starting point for discussion.

The purpose of this patch is to add a minimal change to the Black Magic Probe firmware that makes it easier to build out-of-tree firmware extensions, e.g. to include functionality in the debug probe that is very specific to a particular target board and firmware.

As a working title, these these extensions are called 'applets'.

See documentation included in applet.h comments, and the files in example_applet/

### CODE REVIEW

**Comment by UweBonnes** [comment]
Whats the difference to #833? How to use? How to build.

**Comment by zwizwa** [comment]
> Whats the difference to #833? How to use? How to build.

Thanks, I wasn't aware of #833. I'll review that first and work on top of it if possible.
If I continue on this path here, I'll submit a test so it would be easier to evaluate.

**Comment by zwizwa** [comment]
Continuing with this since #833 might not be merged as-is due to rights issues.

Reworked to present a minimal change, with an example applet to demonstrate the basic idea.  The logging applet is in active use.

The thing I am not happy with is the location of app_poll(). Any suggestions?

**Comment by zwizwa** [comment]
The patch excluding the example is fairly minimal now. I hope it makes the idea clear. If not I'm happy to clarify more, or reshape it if there are concerns about how this is hooked in.

TODO:
- move example out of tree
- create minimal blue pill board firmware for testing the example logger applet

**Comment by dragonmux** [comment]
Seeing as BMD's architecture has drastically changed since this was proposed, and it hooks into some of the machinery (such as halt polling) improperly (meaning the concept would need re-imagining for it to become viable to even begin to entertain), we are going to close this PR as extensibility is achieved in other ways in-tree already and we want to encourage people to contribute to the tree rather than maintaining their own out-of-tree patch sets wherever possible.

It's a neat idea, but with Flash space at a premium, the reworked packet processing machinery from when this was imagined, and those other considerations in mind, this is not an avenue we wish to explore further at this time. If that changes, however, then we can always re-open this PR or otherwise draw inspiration from it with credit.

**Comment by zwizwa** [comment]
Thanks for the comments. If the weather is right I might pick this up again on top of a more recent branch.

**Pull request closed without merging**
