### PR TITLE
target/renesas: add known id for RA2A1

### LINKED ISSUE #1243: Support for Renesas RA2A1 ?
Trying to use it with Renesas RA2A1 and getting the following:

```
WARNING: "Debug component" !match expected "Generic IP component"
Found renesas chip (R7FA2A1AB3CNF   ) with Flash Root Table and unsupported Part ID 0x1b0 please report it
0x80000000: 0x00000004000a3004 Non ARM component ignored
```

Support for this series ?

### PR DESCRIPTION
**Pull request by perigoso**
Adds id for RA2A1, from #1243 

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [ ] I've tested it to the best of my ability (no hardware, 3rd party testing necessary)
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

closes #1243

### CODE REVIEW

**Review by dragonmux — APPROVED** [review]
LGTM, and it's a low-impact change, so we'll bump it into v1.9 as a bugfix

**Comment by mtk11** [comment]
> @mtk11 If you could test this out to make sure it probes you part successfully

```
Speed set to  4.0000 MHz for SWD
scan_multidrop: true
DP DPIDR 0x5ba02477 (v2 rev0) designer 0x43b partno 0xba
TARGETID 0x001b0447 designer 0x423 partno 0x1b0
RESET_SEQ failed
AP   0: IDR=74770001 CFG=00000000 BASE=4001a003 CSW=43800040 (AHB-AP var0 rev7)
Halt via DHCSR: success 05030003 after 4ms
ROM: Table BASE=0x4001a000 SYSMEM=0x00000001, Manufacturer 423 Partno  1b
0 0xe000e000: Debug component - Cortex-M23 (System Control Space) (PIDR = 0x00000004000bbd20  DEVTYPE = 0x00 ARCHID = 0x2a04)
WARNING: "Debug component" !match expected "Generic IP component"
-> cortexm_probe
CPUID 0x411cd200 (M23 var 1 rev 0)
Calling renesas_probe
1 0xe0001000: Debug component - Cortex-M23 (Data Watchpoint and Trace) (PIDR = 0x00000004000bbd20  DEVTYPE = 0x00 ARCHID = 0x1a02)
2 0xe0002000: Debug component - Cortex-M23 (Breakpoint Unit) (PIDR = 0x00000004000bbd20  DEVTYPE = 0x00 ARCHID = 0x1a03)
3 0x40019000: Debug component - Cortex-M23 (Micro Trace Buffer) (PIDR = 0x00000004000bbd20  DEVTYPE = 0x31 ARCHID = 0x0a31)
ROM: Table END
AP   1: IDR=44770002 CFG=00000000 BASE=80000003 CSW=80000040 (AHB-AP var0 rev4)
0x80000000: 0x00000004000a3004 Non ARM component ignored
***  1      R7FA2A1AB3CNF    M23
RAM   Start: 0x20000000 length = 0x8000
```
No error reported. 

@perigoso Do you expect the flashing soon to be fixed ?

**Comment by dragonmux** [comment]
ah, also.. we know what's going on with the SCS type warning for Cortex-M23.. it's to do with the ADIv5 component table at the top of adiv5.c - it was supposed to be addressed by f4345e47 but obviously that didn't go quite far enough

**Comment by mtk11** [comment]
@ perigoso  Sure, I can test it. Just let me know what needs to be done.

**Comment by mtk11** [comment]
For now just RA2A1.

**Pull request merged**
