### PR TITLE
[WIP] ARMv7-A/R fixes needed to work with Cortex-R5

### PR DESCRIPTION
**Pull request by gsmcmullin**

### CODE REVIEW

**Comment by perigoso** [comment]
what's the deal with this? does it need anything?

**Comment by dragonmux** [comment]
If possible, if someone has some suitable hardware.. it needs testing.. but mostly it needs rebasing, build testing and merging.

**Comment by dragonmux** [comment]
In the interests of seeing this in, we're going to rebase it and merge it in the v1.10 cycle and let people holler in complaint if it breaks something

**Review by dragonmux — APPROVED** [review]
These changes seem reasonable and harmless enough, merging.

**Review by dragonmux — APPROVED** [review]

**Pull request merged**
